name: waaa
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter
  intl: any


  flutter_bloc:
  bloc:
  hive: ^2.2.3
  flutter_svg: ^2.0.4

  # Icons
  flutter_feather_icons: ^2.0.0
  cupertino_icons: ^1.0.2

  # Forms
  pin_code_fields: ^7.4.0
  country_picker: ^2.0.20
  language_picker: ^0.4.3
  group_button: ^5.2.2
  scroll_date_picker: ^3.7.0
  flutter_datetime_picker: ^1.5.1
  image_picker: ^0.8.7
  path_provider: ^2.0.13

  # Fonts
  google_fonts: ^4.0.3

  equatable: ^2.0.3
  flutter_lints: ^2.0.0

  json_serializable: ^6.6.1
  json_annotation: ^4.8.0
  build_runner: ^2.3.3
  graphql_flutter: ^5.1.2

  get_it: ^7.2.0
  shared_preferences: ^2.0.18

  # AWS API
  amplify_flutter: ^0.6.4
  amplify_auth_cognito: ^0.6.4
  amplify_api: ^0.6.0
  amplify_storage_s3: ^0.6.0

  # Internet
  internet_connection_checker: ^1.0.0+1
  aws_common: ^0.1.1

  #Maps
  flutter_map: ^3.1.0
  latlong2: ^0.8.1

  #Style 
  another_flushbar: ^1.12.29


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/images/





  #   - images/a_dot_ham.jpeg
  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
 
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
